development:
  adapter: postgresql
  encoding: unicode
  database: iz_development
  pool: 5
  username: postgres
  password: postgres
test:
  adapter: postgresql
  encoding: unicode
  database: iz_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf-8
  database: iz_production
  pool: 5
  username: postgres
  password: postgres
