development:
  adapter: postgresql
  encoding: unicode
  database: iz_development
  pool: 5
  username: postgres
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: iz_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: iz_production
  pool: 5
  username: postgres
  password:
